import 'package:e_commerce/src/model/bottom_navy_bar_item.dart';
import 'package:e_commerce/src/model/recommended_product.dart';
import 'package:e_commerce/src/model/product_category.dart';
import 'package:e_commerce/src/model/product.dart';
import 'package:flutter/material.dart';

class AppData {
  const AppData._();

  static String dummyText =
      'Lorem Ipsum is simply dummy text of the printing and typesetting'
      ' industry. Lorem Ipsum has been the industry\'s standard dummy text'
      ' ever since the 1500s, when an unknown printer took a galley of type'
      ' and scrambled it to make a type specimen book.';

  static List<Product> products = [
    Product(
      name: 'Chocolate Milkshake',
      price: 15000,
      about: dummyText,
      isAvailable: true,
      off: 12000,
      quantity: 0,
      images: "assets/images/coklat.jpg",
      isFavorite: true,
      rating: 4,
      type: ProductType.noncoffee,
    ),
    Product(
      name: 'Greentea Milkshake',
      price: 13000,
      about: dummyText,
      isAvailable: true,
      off: 12000,
      quantity: 0,
      images: "assets/images/greentea.jpg",
      isFavorite: true,
      rating: 4,
      type: ProductType.noncoffee,
    ),
    Product(
      name: 'Oreo Milkshake',
      price: 15000,
      about: dummyText,
      isAvailable: true,
      off: 13000,
      quantity: 0,
      images: "assets/images/oreo.jpg",
      isFavorite: false,
      rating: 4,
      type: ProductType.noncoffee,
    ),
    Product(
      name: 'Red Velvet Milkshake',
      price: 15000,
      about: dummyText,
      isAvailable: true,
      off: 13000,
      quantity: 0,
      images: "assets/images/red_velvet.jpg",
      isFavorite: true,
      rating: 5,
      type: ProductType.noncoffee,
    ),
    Product(
      name: 'Taro Milkshake',
      price: 15000,
      about: dummyText,
      isAvailable: false,
      off: 13000,
      quantity: 0,
      images: "assets/images/taro.jpg",
      isFavorite: false,
      rating: 3,
      type: ProductType.noncoffee,
    ),
    Product(
      name: 'Double Shoot Coffee',
      price: 10000,
      about: dummyText,
      isAvailable: false,
      off: 8000,
      quantity: 0,
      images: "assets/images/double_shoot.jpg",
      isFavorite: false,
      rating: 3,
      type: ProductType.coffeebased,
    ),
    Product(
      name: 'Iced Milk Coffee (1 Liter)',
      price: 130000,
      about: dummyText,
      isAvailable: true,
      off: 100000,
      quantity: 0,
      images: "assets/images/literan.jpg",
      isFavorite: true,
      rating: 4,
      type: ProductType.coffeebased,
    ),
    Product(
      name: 'Single Shot Coffee',
      price: 5000,
      about: dummyText,
      isAvailable: true,
      off: 4000,
      quantity: 0,
      images: "assets/images/single_shoot.jpg",
      isFavorite: false,
      rating: 3,
      type: ProductType.coffeebased,
    ),
    Product(
      name: 'V60 Coffee',
      price: 15000,
      about: dummyText,
      isAvailable: true,
      off: 14000,
      quantity: 0,
      images: "assets/images/v60.jpg",
      isFavorite: true,
      rating: 4,
      type: ProductType.coffeebased,
    ),
    Product(
      name: 'Japanese Coffee',
      price: 15000,
      about: dummyText,
      isAvailable: true,
      off: 14000,
      quantity: 0,
      images: "assets/images/japanese.jpg",
      isFavorite: true,
      rating: 4,
      type: ProductType.coffeebased,
    ),
    Product(
      name: 'Vietnam Drip',
      price: 13000,
      about: dummyText,
      isAvailable: true,
      off: 12000,
      quantity: 0,
      images: "assets/images/vietnam_drip.jpg",
      isFavorite: true,
      rating: 5,
      type: ProductType.coffeebased,
    ),
    Product(
      name: 'Toraja Coffee Beans',
      price: 200000,
      about: dummyText,
      isAvailable: true,
      off: 195000,
      quantity: 0,
      images: "assets/images/toraja.jpg",
      isFavorite: true,
      rating: 4,
      type: ProductType.beans,
    ),
    Product(
      name: 'Kintamani Coffee Beans',
      price: 250000,
      about: dummyText,
      isAvailable: true,
      off: 230000,
      quantity: 0,
      images: "assets/images/kintamani.jpg",
      isFavorite: true,
      rating: 5,
      type: ProductType.beans,
    ),
    Product(
      name: 'Peabery Coffee Beans',
      price: 300000,
      about: dummyText,
      isAvailable: false,
      off: 280000,
      quantity: 0,
      images: "assets/images/peabery.jpg",
      isFavorite: false,
      rating: 3,
      type: ProductType.beans,
    ),
    Product(
      name: 'Gayo Wine Coffee Beans',
      price: 200000,
      about: dummyText,
      isAvailable: true,
      off: 180000,
      quantity: 0,
      images: "assets/images/gayo_wine.jpg",
      isFavorite: true,
      rating: 5,
      type: ProductType.beans,
    ),
    Product(
      name: 'V60 Equipment Fullset',
      price: 500000,
      about: dummyText,
      isAvailable: true,
      off: 400000,
      quantity: 0,
      images: "assets/images/v60_fullset.jpg",
      isFavorite: false,
      rating: 4,
      type: ProductType.equipment,
    ),
    Product(
      name: 'Grinder Coffee',
      price: 1500000,
      about: dummyText,
      isAvailable: true,
      off: 1200000,
      quantity: 0,
      images: "assets/images/grinder.png",
      isFavorite: true,
      rating: 4,
      type: ProductType.equipment,
    ),
  ];

  static List<ProductCategory> categories = [
    ProductCategory(
      ProductType.all,
      true,
      "All",
    ),
    ProductCategory(
      ProductType.noncoffee,
      false,
      "Non Coffee",
    ),
    ProductCategory(
      ProductType.coffeebased,
      false,
      "Coffee Based",
    ),
    ProductCategory(
      ProductType.beans,
      false,
      "Coffee Beans",
    ),
    ProductCategory(
      ProductType.equipment,
      false,
      "Equipment",
    ),
  ];

  static List<Color> randomColors = [
    const Color(0xFFFCE4EC),
    const Color(0xFFF3E5F5),
    const Color(0xFFEDE7F6),
    const Color(0xFFE3F2FD),
    const Color(0xFFE0F2F1),
    const Color(0xFFF1F8E9),
    const Color(0xFFFFF8E1),
    const Color(0xFFECEFF1),
  ];

  static List<BottomNavyBarItem> bottomNavyBarItems = [
    BottomNavyBarItem(
      "Home",
      const Icon(Icons.home),
      const Color(0xFF1750ac),
      Colors.grey,
    ),
    BottomNavyBarItem(
      "Favorite",
      const Icon(Icons.favorite),
      const Color(0xFF1750ac),
      Colors.grey,
    ),
    BottomNavyBarItem(
      "Cart",
      const Icon(Icons.shopping_cart),
      const Color(0xFF1750ac),
      Colors.grey,
    ),
    BottomNavyBarItem(
      "Profile",
      const Icon(Icons.person),
      const Color(0xFF1750ac),
      Colors.grey,
    ),
  ];

  static List<RecommendedProduct> recommendedProducts = [
    RecommendedProduct(
      imagePath: "",
      cardBackgroundColor: const Color(0xFFEC6813),
    ),
    RecommendedProduct(
      imagePath: "",
      cardBackgroundColor: const Color(0xFF3081E1),
      buttonBackgroundColor: const Color(0xFF9C46FF),
      buttonTextColor: Colors.white,
    ),
  ];
}
